---
name: monkeyplug-build-push-whisper-ghcr

on:
  push:
    branches:
      - 'main'
    paths:
      - '!.github/workflows/monkeyplug-build-push-vosk-ghcr.yml'
      - '!.github/workflows/publish-to-pypi.yml'
  pull_request:
  workflow_dispatch:
  repository_dispatch:
  schedule:
    - cron: '0 12 15 * *'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ghcr.io/${{ github.repository_owner }}/monkeyplug
  IMAGE_ARCH: amd64
  REPO_CONTEXT: .
  REPO_CONTAINERFILE: ./docker/Dockerfile

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.matrix.outputs.value }}
    steps:
      -
        name: Cancel previous run in progress
        id: cancel-previous-runs
        uses: styfle/cancel-workflow-action@0.11.0
        with:
          ignore_sha: true
          all_but_latest: true
          access_token: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Enumerate Whisper models
        id: matrix
        run: |
          echo "value=[\"tiny.en\", \"tiny\", \"base.en\", \"base\", \"small.en\", \"small\", \"medium.en\", \"medium\", \"large-v1\", \"large-v2\", \"large-v3\", \"large\"]" >> $GITHUB_OUTPUT
      -
        run: |
          echo "${{ steps.matrix.outputs.value }}"
  buildah:
    needs: [ setup ]
    runs-on: ubuntu-latest
    permissions:
      actions: write
      packages: write
      contents: read
      security-events: write
    strategy:
      matrix:
        value: ${{fromJSON(needs.setup.outputs.matrix)}}
    steps:
      -
        name: Checkout
        id: repo-checkout
        uses: actions/checkout@v3
      -
        name: Set up QEMU
        id: setup-qemu
        uses: docker/setup-qemu-action@v2
      -
        name: Log in to registry
        id: registry-login
        uses: redhat-actions/podman-login@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Build (Whisper)
        id: build-whisper-image
        uses: redhat-actions/buildah-build@v2
        with:
          image: ${{ env.IMAGE_NAME }}
          tags: whisper-${{ matrix.value }}
          context: ${{ env.REPO_CONTEXT }}
          containerfiles: ${{ env.REPO_CONTAINERFILE }}
          archs: ${{ env.IMAGE_ARCH }}
          target: whisper
          build-args: |
            WHISPER_MODEL_NAME=${{ matrix.value }}
      -
        name: Run Trivy vulnerability scanner (Whisper)
        id: trivy-scan
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'image'
          image-ref: ${{ steps.build-vosk-image.outputs.image }}:${{ steps.build-whisper-image.outputs.tags }}
          format: 'sarif'
          output: 'trivy-results.sarif'
          severity: 'HIGH,CRITICAL'
          vuln-type: 'os,library'
          hide-progress: true
          ignore-unfixed: true
          exit-code: '0'
      -
        name: Upload Trivy scan results to GitHub Security tab (Whisper)
        uses: github/codeql-action/upload-sarif@v2
        if: always()
        with:
          sarif_file: 'trivy-results.sarif'
      -
        name: Push (Whisper)
        id: push-whisper-image
        uses: redhat-actions/push-to-registry@v2
        with:
          image: ${{ steps.build-whisper-image.outputs.image }}
          tags: ${{ steps.build-whisper-image.outputs.tags }}
          registry: ${{ env.REGISTRY }}
