---
name: monkeyplug-build-push-vosk-ghcr

on:
  push:
    branches:
      - 'main'
    paths:
      - '**'
      - '!.github/workflows/monkeyplug-build-push-whisper-ghcr.yml'
      - '!.github/workflows/publish-to-pypi.yml'
  pull_request:
  workflow_dispatch:
  repository_dispatch:
  schedule:
    - cron: '0 12 15 * *'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ghcr.io/${{ github.repository_owner }}/monkeyplug
  IMAGE_ARCH: amd64
  REPO_CONTEXT: .
  REPO_CONTAINERFILE: ./docker/Dockerfile

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.matrix.outputs.value }}
    steps:
      -
        name: Cancel previous run in progress
        id: cancel-previous-runs
        uses: styfle/cancel-workflow-action@0.11.0
        with:
          ignore_sha: true
          all_but_latest: true
          access_token: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Enumerate VOSK URLs
        id: matrix
        run: |
          echo "value=[\"small~https://alphacephei.com/kaldi/models/vosk-model-small-en-us-0.15.zip\", \"large~http://alphacephei.com/vosk/models/vosk-model-en-us-0.22.zip\"]" >> $GITHUB_OUTPUT
      -
        run: |
          echo "${{ steps.matrix.outputs.value }}"
  buildah:
    needs: [ setup ]
    runs-on: ubuntu-latest
    permissions:
      actions: write
      packages: write
      contents: read
      security-events: write
    strategy:
      matrix:
        value: ${{fromJSON(needs.setup.outputs.matrix)}}
    steps:
      -
        name: Checkout
        id: repo-checkout
        uses: actions/checkout@v3
      -
        name: Set up QEMU
        id: setup-qemu
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        id: setup-docker-buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver-opts: |
            image=moby/buildkit:master
      -
        name: Extract tag name
        shell: bash
        run: echo "tag=$(echo ${{ matrix.value }} | cut -d'~' -f1)" >> $GITHUB_OUTPUT
        id: extract_tag
      -
        name: Extract model URL
        shell: bash
        run: echo "url=$(echo ${{ matrix.value }} | cut -d'~' -f2)" >> $GITHUB_OUTPUT
        id: extract_url
      -
        name: Free up space
        shell: bash
        id: remove_useless_stuff
        run: |
          sudo rm -rf /usr/share/dotnet \
                      /usr/local/lib/android \
                      /opt/ghc \
                      /usr/local/share/boost \
                      "$AGENT_TOOLSDIRECTORY" || true
      -
        name: ghcr.io login
        id: ghcr-io-login
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Build and push Monkeyplug (VOSK) image
        id: build-and-push
        uses: docker/build-push-action@v5
        with:
          context: ./malcolm-iso
          push: true
          tags: ${{ env.IMAGE_NAME }}:vosk-${{ steps.extract_tag.outputs.tag }}
          context: ${{ env.REPO_CONTEXT }}
          file: ${{ env.REPO_CONTAINERFILE }}
          platforms: ${{ env.IMAGE_ARCH }}
          target: vosk
          build-args: |
            VOSK_MODEL_URL=${{ steps.extract_url.outputs.url }}
